### ISSUE TITLE
Support building URLs and Git tags from $major_version, $minor_version and $patch_version

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/flatpak-external-data-checker#134]
The download URLs of source archives of projects hosted on Sourceforge sometimes contain the pattern $major_version.$minor_version, without the $patch_version:

https://sourceforge.net/projects/qrupdate/files/qrupdate/1.2/qrupdate-1.1.2.tar.gz
https://downloads.sourceforge.net/project/flightgear/release-2020.3/flightgear-2020.3.6.tar.bz2

Thus, it would be nice if one could use these variables for the URL template.

**Comment by gasinvein** [comment]
I guess you can use HTML Checker url pattern against Sourceforge rss feed, it contains full urls.
Untested, but something like this should do:
```yaml
x-checker-data:
  type: html
  url: https://sourceforge.net/projects/flightgear/rss
  version-pattern: <link>https://sourceforge.net/projects/flightgear/files/release-[\d\.]+/flightgear-([\d\.]+\d).tar.bz2/download</link>
  url-pattern: <link>(https://sourceforge.net/projects/flightgear/files/release-[\d\.]+/flightgear-[\d\.]+\d.tar.bz2)/download</link>
```
